name: lunar-e2e-pin-rotation-feba423d2
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened feba423d2'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-feba423d2'
    runs-on: localdev-e2e-test-37907771582-1-github-2-e2e
    steps:
      - run: /bin/echo 'pin rotation CI feba423d2'
