name: lunar-e2e-pin-rotation-5276d9502
on:
  pull_request:
    types: [opened, labeled]
permissions:
  contents: read
jobs:
  ready:
    if: github.event.action == 'opened'
    runs-on: ubuntu-24.04
    steps:
      - run: /bin/echo 'pin rotation PR opened 5276d9502'
  ci:
    if: github.event.action == 'labeled' && github.event.label.name == 'e2e-pin-rotation-5276d9502'
    runs-on: localdev-e2e-test-37915235339-1-github-2-e2e
    steps:
      - run: /bin/echo 'pin rotation CI 5276d9502'
